version: 0.2

phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  pre_build:
    commands:
      - echo Running pre-build commands...
      - npm install -g serve
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Installing dependencies for production...
      - npm prune --production

artifacts:
  files:
    - 'package.json'
    - 'server.js'
    - 'Procfile'
    - 'dist/**/*'
  name: myapp-$(date +%Y-%m-%d)

cache:
  paths:
    - node_modules/**/*
